create table users (
  username varchar(50) not null primary key,
  password varchar(250) not null,
  enabled boolean not null
);

create table authorities (
  username varchar(50) not null,
  authority varchar(50) not null,
  constraint fk_authorities_users foreign key (username) references users (username)
);
create unique index ix_auth_username
on authorities (username, authority);

CREATE TABLE NOTE (
  ID      INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CONTENT VARCHAR(144),
  username varchar(50)
);

CREATE TABLE COMMENTARY (
  ID      INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CONTENT VARCHAR(144),
  username varchar(50),
  ID_NOTE INT
);

CREATE TABLE COLLABORATEUR (
    ID INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CollaborateurA VARCHAR(50),
    CollaborateurB VARCHAR(50)
);

CREATE TABLE NOTEINCOLLAB (
    ID INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_NOTE INT,
    Collaborateur VARCHAR(50)
);

-- create user
INSERT INTO users values ('usertestB', 'usertestB', true);
insert into authorities values ('usertestB', 'USER');

INSERT INTO users values ('usertestA', 'usertestA', true);
insert into authorities values ('usertestA', 'USER');

INSERT INTO NOTE VALUES(1, 'Ceci est une note de usertestB partagée avec usertestA', 'usertestB') ;

INSERT INTO NOTEINCOLLAB VALUES(1, 1, 'usertestA') ;